const MIN_RGB_DIST = 125;
const MAX_RGB_DIST = 175;
const VICTORY_DIST = 25;
const MAX_RGB_INCREASE_BY_NUMBER_DELTA = 100;
const MAX_RGB_INCREASE_BY_COEFF_DELTA = 60;

const WRAP_CHAR = String.fromCharCode(173);